New ee place skill
facebookresearch/spot-sim2real pull request #233
Opened 2024-10-04 23:55 UTC by Achuthankrishna

This branch consists of code changes for incorporating new semantic place ee skill into main, which was tested in lab and also in apartment with nav-pick-nav-place . The results can be found using this [link ](https://docs.google.com/spreadsheets/d/18cxLUSRR4FSJ3yffSowWsWS4hxU-mPm2jQheeB8TyK8/edit?usp=sharing).

2024-10-09 16:11 UTC, joannetruong commented on spot_rl_experiments/spot_rl/envs/base_env.py
> +    # New function to turn wrist to clip it to 160 deg (as per BD Documentation)
We can move this to place_env.py within the SemanticPlaceEE class

2024-10-09 16:11 UTC, joannetruong commented on spot_rl_experiments/spot_rl/envs/base_env.py
> +        arm_positions[-1] = arm_positions[-1] + np.deg2rad(90)
arm_positions[-1] += np.deg2rad(90)

2024-10-09 16:12 UTC, joannetruong commented on spot_rl_experiments/spot_rl/envs/place_env.py
> +        self.ee_env = False
remove

2024-10-09 16:14 UTC, joannetruong commented on spot_rl_experiments/spot_rl/envs/place_env.py
> +                    self.config.INITIAL_ARM_JOINT_ANGLES_SEMANTIC_PLACE_EE
let's make a `decide_init_arm_joint` function in `SpotSemanticPlaceEEEnv` to override this

2024-10-09 16:14 UTC, joannetruong commented on spot_rl_experiments/spot_rl/envs/place_env.py
> +            self.turn_wrist_place()
let's make a new `step` function in `SpotSemanticPlaceEEEnv` to override this

2024-10-09 16:15 UTC, joannetruong requested changes
Let's create new functions in `SpotSemanticPlaceEEEnv` to include the changes instead of modifying `SpotSemanticPlaceEnv` directly

2024-10-25 23:03 UTC, Achuthankrishna commented
This PR is merged into main with #244 . Closing this PR.

2024-10-25 23:04 UTC, closed without merging